name = "UnitfulMR"
uuid = "84966e9a-a839-11e9-29d5-57fe5a7e36c2"
authors = ["Ray-Lab <tianrluo@users.noreply.github.com>"]
version = "0.1.1"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "≥ 0.7"
